# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, project_name: str=None):  # noqa: E501
        """DataInput - a model defined in Swagger

        :param id: The id of this DataInput.  # noqa: E501
        :type id: str
        :param project_name: The project_name of this DataInput.  # noqa: E501
        :type project_name: str
        """
        self.swagger_types = {
            'id': str,
            'project_name': str
        }

        self.attribute_map = {
            'id': 'id',
            'project_name': 'project_name'
        }

        self._id = id
        self._project_name = project_name

    @classmethod
    def from_dict(cls, dikt) -> 'DataInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataInput of this DataInput.  # noqa: E501
        :rtype: DataInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DataInput.

        File UUID  # noqa: E501

        :return: The id of this DataInput.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DataInput.

        File UUID  # noqa: E501

        :param id: The id of this DataInput.
        :type id: str
        """

        self._id = id

    @property
    def project_name(self) -> str:
        """Gets the project_name of this DataInput.

        Name of the project the data file belongs to  # noqa: E501

        :return: The project_name of this DataInput.
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name: str):
        """Sets the project_name of this DataInput.

        Name of the project the data file belongs to  # noqa: E501

        :param project_name: The project_name of this DataInput.
        :type project_name: str
        """

        self._project_name = project_name
