# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Empty(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: object=None):  # noqa: E501
        """Empty - a model defined in Swagger

        :param data: The data of this Empty.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'data': object
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Empty':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Empty of this Empty.  # noqa: E501
        :rtype: Empty
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> object:
        """Gets the data of this Empty.


        :return: The data of this Empty.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this Empty.


        :param data: The data of this Empty.
        :type data: object
        """

        self._data = data
