# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: str=None, error_description: str=None, user_message: str=None):  # noqa: E501
        """Error - a model defined in Swagger

        :param error: The error of this Error.  # noqa: E501
        :type error: str
        :param error_description: The error_description of this Error.  # noqa: E501
        :type error_description: str
        :param user_message: The user_message of this Error.  # noqa: E501
        :type user_message: str
        """
        self.swagger_types = {
            'error': str,
            'error_description': str,
            'user_message': str
        }

        self.attribute_map = {
            'error': 'error',
            'error_description': 'error_description',
            'user_message': 'user_message'
        }

        self._error = error
        self._error_description = error_description
        self._user_message = user_message

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this Error.

        An error code  # noqa: E501

        :return: The error of this Error.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this Error.

        An error code  # noqa: E501

        :param error: The error of this Error.
        :type error: str
        """

        self._error = error

    @property
    def error_description(self) -> str:
        """Gets the error_description of this Error.

        A human readable description of the error  # noqa: E501

        :return: The error_description of this Error.
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description: str):
        """Sets the error_description of this Error.

        A human readable description of the error  # noqa: E501

        :param error_description: The error_description of this Error.
        :type error_description: str
        """

        self._error_description = error_description

    @property
    def user_message(self) -> str:
        """Gets the user_message of this Error.

        Optional message to display to user  # noqa: E501

        :return: The user_message of this Error.
        :rtype: str
        """
        return self._user_message

    @user_message.setter
    def user_message(self, user_message: str):
        """Sets the user_message of this Error.

        Optional message to display to user  # noqa: E501

        :param user_message: The user_message of this Error.
        :type user_message: str
        """

        self._user_message = user_message
