# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.jobs_data import JobsData  # noqa: F401,E501
from swagger_server import util


class Jobs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: JobsData=None):  # noqa: E501
        """Jobs - a model defined in Swagger

        :param data: The data of this Jobs.  # noqa: E501
        :type data: JobsData
        """
        self.swagger_types = {
            'data': JobsData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Jobs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Jobs of this Jobs.  # noqa: E501
        :rtype: Jobs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> JobsData:
        """Gets the data of this Jobs.


        :return: The data of this Jobs.
        :rtype: JobsData
        """
        return self._data

    @data.setter
    def data(self, data: JobsData):
        """Sets the data of this Jobs.


        :param data: The data of this Jobs.
        :type data: JobsData
        """

        self._data = data
