# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.model404_error_error_data import Model404ErrorErrorData  # noqa: F401,E501
from swagger_server import util


class Model404Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: str=None, error_description: str=None, user_message: str=None, error_data: Model404ErrorErrorData=None):  # noqa: E501
        """Model404Error - a model defined in Swagger

        :param error: The error of this Model404Error.  # noqa: E501
        :type error: str
        :param error_description: The error_description of this Model404Error.  # noqa: E501
        :type error_description: str
        :param user_message: The user_message of this Model404Error.  # noqa: E501
        :type user_message: str
        :param error_data: The error_data of this Model404Error.  # noqa: E501
        :type error_data: Model404ErrorErrorData
        """
        self.swagger_types = {
            'error': str,
            'error_description': str,
            'user_message': str,
            'error_data': Model404ErrorErrorData
        }

        self.attribute_map = {
            'error': 'error',
            'error_description': 'error_description',
            'user_message': 'user_message',
            'error_data': 'error_data'
        }

        self._error = error
        self._error_description = error_description
        self._user_message = user_message
        self._error_data = error_data

    @classmethod
    def from_dict(cls, dikt) -> 'Model404Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 404Error of this Model404Error.  # noqa: E501
        :rtype: Model404Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this Model404Error.

        An error code  # noqa: E501

        :return: The error of this Model404Error.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this Model404Error.

        An error code  # noqa: E501

        :param error: The error of this Model404Error.
        :type error: str
        """

        self._error = error

    @property
    def error_description(self) -> str:
        """Gets the error_description of this Model404Error.

        A human readable description of the error  # noqa: E501

        :return: The error_description of this Model404Error.
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description: str):
        """Sets the error_description of this Model404Error.

        A human readable description of the error  # noqa: E501

        :param error_description: The error_description of this Model404Error.
        :type error_description: str
        """

        self._error_description = error_description

    @property
    def user_message(self) -> str:
        """Gets the user_message of this Model404Error.

        Optional message to display to user  # noqa: E501

        :return: The user_message of this Model404Error.
        :rtype: str
        """
        return self._user_message

    @user_message.setter
    def user_message(self, user_message: str):
        """Sets the user_message of this Model404Error.

        Optional message to display to user  # noqa: E501

        :param user_message: The user_message of this Model404Error.
        :type user_message: str
        """

        self._user_message = user_message

    @property
    def error_data(self) -> Model404ErrorErrorData:
        """Gets the error_data of this Model404Error.


        :return: The error_data of this Model404Error.
        :rtype: Model404ErrorErrorData
        """
        return self._error_data

    @error_data.setter
    def error_data(self, error_data: Model404ErrorErrorData):
        """Sets the error_data of this Model404Error.


        :param error_data: The error_data of this Model404Error.
        :type error_data: Model404ErrorErrorData
        """

        self._error_data = error_data
