# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Model404ErrorData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, missing_fields: List[str]=None):  # noqa: E501
        """Model404ErrorData - a model defined in Swagger

        :param missing_fields: The missing_fields of this Model404ErrorData.  # noqa: E501
        :type missing_fields: List[str]
        """
        self.swagger_types = {
            'missing_fields': List[str]
        }

        self.attribute_map = {
            'missing_fields': 'missing_fields'
        }

        self._missing_fields = missing_fields

    @classmethod
    def from_dict(cls, dikt) -> 'Model404ErrorData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 404ErrorData of this Model404ErrorData.  # noqa: E501
        :rtype: Model404ErrorData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def missing_fields(self) -> List[str]:
        """Gets the missing_fields of this Model404ErrorData.


        :return: The missing_fields of this Model404ErrorData.
        :rtype: List[str]
        """
        return self._missing_fields

    @missing_fields.setter
    def missing_fields(self, missing_fields: List[str]):
        """Sets the missing_fields of this Model404ErrorData.


        :param missing_fields: The missing_fields of this Model404ErrorData.
        :type missing_fields: List[str]
        """

        self._missing_fields = missing_fields
