# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status_data import StatusData  # noqa: F401,E501
from swagger_server import util


class Status(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: StatusData=None):  # noqa: E501
        """Status - a model defined in Swagger

        :param data: The data of this Status.  # noqa: E501
        :type data: StatusData
        """
        self.swagger_types = {
            'data': StatusData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Status':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Status of this Status.  # noqa: E501
        :rtype: Status
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> StatusData:
        """Gets the data of this Status.


        :return: The data of this Status.
        :rtype: StatusData
        """
        return self._data

    @data.setter
    def data(self, data: StatusData):
        """Sets the data of this Status.


        :param data: The data of this Status.
        :type data: StatusData
        """

        self._data = data
