# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status_data import StatusData  # noqa: F401,E501
from swagger_server import util


class StatusArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: List[StatusData]=None):  # noqa: E501
        """StatusArray - a model defined in Swagger

        :param data: The data of this StatusArray.  # noqa: E501
        :type data: List[StatusData]
        """
        self.swagger_types = {
            'data': List[StatusData]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'StatusArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StatusArray of this StatusArray.  # noqa: E501
        :rtype: StatusArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[StatusData]:
        """Gets the data of this StatusArray.


        :return: The data of this StatusArray.
        :rtype: List[StatusData]
        """
        return self._data

    @data.setter
    def data(self, data: List[StatusData]):
        """Sets the data of this StatusArray.


        :param data: The data of this StatusArray.
        :type data: List[StatusData]
        """

        self._data = data
