# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.suggest_data import SuggestData  # noqa: F401,E501
from swagger_server import util


class Suggest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: SuggestData=None):  # noqa: E501
        """Suggest - a model defined in Swagger

        :param data: The data of this Suggest.  # noqa: E501
        :type data: SuggestData
        """
        self.swagger_types = {
            'data': SuggestData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Suggest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Suggest of this Suggest.  # noqa: E501
        :rtype: Suggest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> SuggestData:
        """Gets the data of this Suggest.


        :return: The data of this Suggest.
        :rtype: SuggestData
        """
        return self._data

    @data.setter
    def data(self, data: SuggestData):
        """Sets the data of this Suggest.


        :param data: The data of this Suggest.
        :type data: SuggestData
        """

        self._data = data
