# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.suggest_data_jobs import SuggestDataJobs  # noqa: F401,E501
from swagger_server import util


class SuggestData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, jobs: List[SuggestDataJobs]=None):  # noqa: E501
        """SuggestData - a model defined in Swagger

        :param jobs: The jobs of this SuggestData.  # noqa: E501
        :type jobs: List[SuggestDataJobs]
        """
        self.swagger_types = {
            'jobs': List[SuggestDataJobs]
        }

        self.attribute_map = {
            'jobs': 'jobs'
        }

        self._jobs = jobs

    @classmethod
    def from_dict(cls, dikt) -> 'SuggestData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuggestData of this SuggestData.  # noqa: E501
        :rtype: SuggestData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jobs(self) -> List[SuggestDataJobs]:
        """Gets the jobs of this SuggestData.


        :return: The jobs of this SuggestData.
        :rtype: List[SuggestDataJobs]
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs: List[SuggestDataJobs]):
        """Sets the jobs of this SuggestData.


        :param jobs: The jobs of this SuggestData.
        :type jobs: List[SuggestDataJobs]
        """

        self._jobs = jobs
