# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.training_response_data import TrainingResponseData  # noqa: F401,E501
from swagger_server import util


class TrainingResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data: TrainingResponseData=None):  # noqa: E501
        """TrainingResponse - a model defined in Swagger

        :param data: The data of this TrainingResponse.  # noqa: E501
        :type data: TrainingResponseData
        """
        self.swagger_types = {
            'data': TrainingResponseData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainingResponse of this TrainingResponse.  # noqa: E501
        :rtype: TrainingResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> TrainingResponseData:
        """Gets the data of this TrainingResponse.


        :return: The data of this TrainingResponse.
        :rtype: TrainingResponseData
        """
        return self._data

    @data.setter
    def data(self, data: TrainingResponseData):
        """Sets the data of this TrainingResponse.


        :param data: The data of this TrainingResponse.
        :type data: TrainingResponseData
        """

        self._data = data
