# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrainingResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, model_id: str=None):  # noqa: E501
        """TrainingResponseData - a model defined in Swagger

        :param model_id: The model_id of this TrainingResponseData.  # noqa: E501
        :type model_id: str
        """
        self.swagger_types = {
            'model_id': str
        }

        self.attribute_map = {
            'model_id': 'model_id'
        }

        self._model_id = model_id

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainingResponse_data of this TrainingResponseData.  # noqa: E501
        :rtype: TrainingResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_id(self) -> str:
        """Gets the model_id of this TrainingResponseData.


        :return: The model_id of this TrainingResponseData.
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id: str):
        """Sets the model_id of this TrainingResponseData.


        :param model_id: The model_id of this TrainingResponseData.
        :type model_id: str
        """

        self._model_id = model_id
